<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>ThaiFontFallback</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <BX>D:\Program Files (x86)\Steam\steamapps\common\Until We Die\BepInEx</BX>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core"><HintPath>$(BX)\core\BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(BX)\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.IL2CPP"><HintPath>$(BX)\core\BepInEx.Unity.IL2CPP.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.Common"><HintPath>$(BX)\core\BepInEx.Unity.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Runtime"><HintPath>$(BX)\core\Il2CppInterop.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Common"><HintPath>$(BX)\core\Il2CppInterop.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2Cppmscorlib"><HintPath>$(BX)\interop\Il2Cppmscorlib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(BX)\interop\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(BX)\interop\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AssetBundleModule"><HintPath>$(BX)\interop\UnityEngine.AssetBundleModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(BX)\interop\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(BX)\interop\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(BX)\interop\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextCoreModule"><HintPath>$(BX)\interop\UnityEngine.TextCoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="I2Localization"><HintPath>$(BX)\interop\I2Localization.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
